### ISSUE TITLE
继续纵容和包庇汤嘉斌只能坏了自己的名声，被他连坐了。还是和他撇清关系。别等到业内，HKU和小红书收到证据锤 引导学生急于求成水论文+包庇掩盖学术造假。

### ISSUE THREAD

**Issue by sdjfsdljnv** [HKUDS/HKUDS#3]
继续纵容和包庇汤嘉斌只能坏了自己的名声，被他连坐了。还是和他撇清关系。别等到业内，HKU和小红书收到证据锤 引导学生急于求成水论文+包庇掩盖学术造假。

**Comment by HKUDS** [comment]
网络不是法外之地，你这种肆意造谣恶意报复的行为，我们会严查让造谣者为自己的行为负责。
